version: '3'

services:

  phm_comms_1:
    container_name: phm_c1
    image: phm_devel
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: "host"
    depends_on:
     - roscore
    environment:
      SYS_ID: 1
      ROS_MASTER_URI: "http://localhost:11311"
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    roslaunch --wait phm_comms phm_comms.launch"

  phm_comms_2:
    container_name: phm_c2
    image: phm_devel
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: "host"
    depends_on:
     - roscore
    environment:
      SYS_ID: 2
      ROS_MASTER_URI: "http://localhost:11311"
    command: >
      /bin/bash -c "source /home/catkin_ws/devel/setup.bash &&
                    roslaunch --wait phm_comms phm_comms.launch"